[package]
name = "vtparse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
unwind = []

[dependencies]
container_of = "0.5.1"

[build-dependencies]
bindgen = "0.66.0"
